[2021-11-21 14:09:36,555] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_table_data.backup_data scheduled__2021-11-20T00:00:00+00:00 [queued]>
[2021-11-21 14:09:36,560] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_table_data.backup_data scheduled__2021-11-20T00:00:00+00:00 [queued]>
[2021-11-21 14:09:36,560] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 14:09:36,560] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-21 14:09:36,560] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 14:09:36,570] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): backup_data> on 2021-11-20 00:00:00+00:00
[2021-11-21 14:09:36,573] {standard_task_runner.py:52} INFO - Started process 42528 to run task
[2021-11-21 14:09:36,583] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_table_data', 'backup_data', 'scheduled__2021-11-20T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_job.py', '--cfg-path', '/tmp/tmpbl3s5t31', '--error-file', '/tmp/tmp6miiipve']
[2021-11-21 14:09:36,584] {standard_task_runner.py:77} INFO - Job 19: Subtask backup_data
[2021-11-21 14:09:36,616] {logging_mixin.py:109} INFO - Running <TaskInstance: load_table_data.backup_data scheduled__2021-11-20T00:00:00+00:00 [running]> on host ubuntu2110.linuxvmimages.local
[2021-11-21 14:09:36,642] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_table_data
AIRFLOW_CTX_TASK_ID=backup_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-20T00:00:00+00:00
[2021-11-21 14:09:36,646] {base.py:70} INFO - Using connection to: id: postgres_default. Host: localhost, Port: 5432, Schema: dailydb, Login: postgres, Password: ***, extra: {}
[2021-11-21 14:09:36,657] {dbapi.py:225} INFO - Running statement: select id, creation_date, sales_value into table transaction_monthly from transaction;, parameters: None
[2021-11-21 14:09:36,659] {dbapi.py:233} INFO - Rows affected: 5
[2021-11-21 14:09:36,668] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=load_table_data, task_id=backup_data, execution_date=20211120T000000, start_date=20211121T070936, end_date=20211121T070936
[2021-11-21 14:09:36,713] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-21 14:09:36,725] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
