[2021-11-21 14:09:34,221] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_table_data.load_initial_data scheduled__2021-11-20T00:00:00+00:00 [queued]>
[2021-11-21 14:09:34,235] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_table_data.load_initial_data scheduled__2021-11-20T00:00:00+00:00 [queued]>
[2021-11-21 14:09:34,235] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 14:09:34,235] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-21 14:09:34,235] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 14:09:34,247] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): load_initial_data> on 2021-11-20 00:00:00+00:00
[2021-11-21 14:09:34,252] {standard_task_runner.py:52} INFO - Started process 42524 to run task
[2021-11-21 14:09:34,256] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_table_data', 'load_initial_data', 'scheduled__2021-11-20T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_job.py', '--cfg-path', '/tmp/tmpx2yp3c0k', '--error-file', '/tmp/tmpzi4as89q']
[2021-11-21 14:09:34,256] {standard_task_runner.py:77} INFO - Job 18: Subtask load_initial_data
[2021-11-21 14:09:34,293] {logging_mixin.py:109} INFO - Running <TaskInstance: load_table_data.load_initial_data scheduled__2021-11-20T00:00:00+00:00 [running]> on host ubuntu2110.linuxvmimages.local
[2021-11-21 14:09:34,322] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_table_data
AIRFLOW_CTX_TASK_ID=load_initial_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-20T00:00:00+00:00
[2021-11-21 14:09:34,326] {base.py:70} INFO - Using connection to: id: postgres_default. Host: localhost, Port: 5432, Schema: dailydb, Login: postgres, Password: ***, extra: {}
[2021-11-21 14:09:34,337] {dbapi.py:225} INFO - Running statement: INSERT INTO transaction (id, creation_date, sales_value) values (1,'2021-11-20', 1000);, parameters: None
[2021-11-21 14:09:34,338] {dbapi.py:233} INFO - Rows affected: 1
[2021-11-21 14:09:34,344] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=load_table_data, task_id=load_initial_data, execution_date=20211120T000000, start_date=20211121T070934, end_date=20211121T070934
[2021-11-21 14:09:34,393] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-21 14:09:34,414] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
